version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password

  drupal:
    image: drupal:latest
    depends_on:
      - mysql
    ports:
      - "8080:80"
    restart: always
